spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true
      platform: h2
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  h2:
    console:
      enabled: true
  session:
    timeout: 240m
    store-type: none
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 5000ms
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 1.0
          max-interval: 10000ms

# MyBatis Configuration (임시 비활성화)
# mybatis:
#   mapper-locations: classpath:mapper/*.xml
#   type-aliases-package: com.skax.eatool.user.infrastructure.mybatis
#   configuration:
#     map-underscore-to-camel-case: true
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    session:
      timeout: 240m # 4시간으로 증가
      cookie:
        http-only: true
        secure: false
        max-age: 14400 # 4시간 (초 단위)
        path: /
        domain: localhost

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.skax.eatool.controller
  paths-to-match: /api/**

# Logging Configuration
logging:
  level:
    com.skax.eatool: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# TPM Service Configuration
service:
  call:
    url: http://localhost:8080
tpmservice:
  url: http://localhost:8080
  timeout: 30
bizaction-map-filename: classpath:config/eatool-config.xml

# Cache Configuration
my:
  cache:
    type: redis # redis 또는 caffeine 선택

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-at-least-256-bits
  expiration: 3600000 # 1시간 (밀리초)

